### ISSUE TITLE
13 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by Befeeter** [RUB-NDS/Terrapin-Scanner#23]
I have analized the i386.exe and virustotal report that it has multiple trojans.

![image](https://github.com/RUB-NDS/Terrapin-Scanner/assets/9259003/eaba2383-7c71-41c3-9cdb-fbbc3491ec68)

**Comment by TrueSkrillor** [comment]
I am aware that some vendors on VirusTotal are detecting our tool. I assume this is because our tool performs a single connection immediately after the program starts (and nothing else), a typical pattern for trojans when downloading additional malware. Also, I'd like to point out that the Windows binaries are not digitally signed, increasing the likelihood of being flagged maliciously.

I'd recommend to review the source code and build from the source if you have any concerns (as for all pre-built binaries). We are providing the binaries for convenience only here.
